# Generated by Django 3.2.7 on 2022-11-14 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=40)),
                ('cardnum', models.IntegerField()),
                ('cardmonth', models.IntegerField()),
                ('cardyear', models.IntegerField()),
                ('cardcode', models.IntegerField()),
                ('job', models.CharField(blank=True, max_length=40, null=True)),
                ('image', models.ImageField(blank=True, upload_to='media')),
                ('gender', models.IntegerField(choices=[(1, 'L:レズビアン'), (2, 'G:ゲイ'), (3, 'B:バイセクシャル'), (4, 'T:トランスジェンダー'), (5, 'Q:クエスチョ二ング')])),
                ('target', models.IntegerField(choices=[(1, 'L:レズビアン'), (2, 'G:ゲイ'), (3, 'B:バイセクシャル'), (4, 'T:トランスジェンダー'), (5, 'Q:クエスチョ二ング')])),
                ('annual_income', models.IntegerField(blank=True, choices=[(1, '50-100'), (2, '100-300'), (3, '300-500'), (4, '500-700'), (5, '700-900'), (6, '900-')], null=True)),
                ('marry', models.IntegerField(blank=True, choices=[(1, '有'), (2, '無')], null=True)),
                ('hobby', models.CharField(blank=True, max_length=40, null=True)),
                ('introduce', models.CharField(blank=True, max_length=300, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
