# Generated by Django 3.2.7 on 2022-11-11 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=3)),
                ('address', models.CharField(max_length=40)),
                ('cardnum', models.IntegerField(blank=True, max_length=16, null=True)),
                ('cardmonth', models.IntegerField(blank=True, max_length=1, null=True)),
                ('cardyear', models.IntegerField(blank=True, max_length=2, null=True)),
                ('cardcode', models.IntegerField(blank=True, max_length=4, null=True)),
                ('job', models.CharField(blank=True, max_length=40, null=True)),
                ('image', models.ImageField(upload_to='profile_pics')),
                ('gender', models.IntegerField(choices=[('L', 'L:レズビアン'), ('G', 'G:ゲイ'), ('B', 'B:バイセクシャル'), ('T', 'T:トランスジェンダー'), ('Q', 'Q:クエスチョ二ング')])),
                ('target', models.IntegerField(choices=[('L', 'L:レズビアン'), ('G', 'G:ゲイ'), ('B', 'B:バイセクシャル'), ('T', 'T:トランスジェンダー'), ('Q', 'Q:クエスチョ二ング')])),
                ('annual_income', models.IntegerField(choices=[(1, '50-100'), (2, '100-300'), (3, '300-500'), (4, '500-700'), (5, '700-900'), (6, '900-')])),
                ('marry', models.IntegerField(choices=[('有', '有'), ('無', '無')])),
                ('hobby', models.CharField(max_length=40)),
                ('introduce', models.CharField(max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
